# Generated by Django 3.1.7 on 2021-04-17 01:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20210416_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='seasons',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)]),
        ),
    ]
